"""Add customers table and link to messages

Revision ID: aba8d08aba8e
Revises: d42ca943b6be
Create Date: 2025-10-17 19:03:41.418135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba8d08aba8e'
down_revision = 'd42ca943b6be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('external_system', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('arr', sa.Float(), nullable=True),
    sa.Column('deal_stage', sa.String(), nullable=True),
    sa.Column('deal_amount', sa.Float(), nullable=True),
    sa.Column('deal_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_probability', sa.Float(), nullable=True),
    sa.Column('customer_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_domain', 'customers', ['domain'], unique=False)
    op.create_index('idx_customers_external', 'customers', ['external_system', 'external_id'], unique=False)
    op.create_index('idx_customers_workspace', 'customers', ['workspace_id'], unique=False)
    op.create_index('idx_customers_workspace_industry', 'customers', ['workspace_id', 'industry'], unique=False)
    op.create_index('idx_customers_workspace_stage', 'customers', ['workspace_id', 'deal_stage'], unique=False)
    op.create_index(op.f('ix_customers_deal_stage'), 'customers', ['deal_stage'], unique=False)
    op.create_index(op.f('ix_customers_domain'), 'customers', ['domain'], unique=False)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_industry'), 'customers', ['industry'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.drop_column('features', 'signals')
    op.add_column('messages', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index('idx_messages_customer', 'messages', ['customer_id'], unique=False)
    op.create_index('idx_messages_workspace_customer', 'messages', ['workspace_id', 'customer_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('idx_messages_workspace_customer', table_name='messages')
    op.drop_index('idx_messages_customer', table_name='messages')
    op.drop_column('messages', 'customer_id')
    op.add_column('features', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_industry'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_domain'), table_name='customers')
    op.drop_index(op.f('ix_customers_deal_stage'), table_name='customers')
    op.drop_index('idx_customers_workspace_stage', table_name='customers')
    op.drop_index('idx_customers_workspace_industry', table_name='customers')
    op.drop_index('idx_customers_workspace', table_name='customers')
    op.drop_index('idx_customers_external', table_name='customers')
    op.drop_index('idx_customers_domain', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###