"""Add ai_insights column to messages

Revision ID: 2254b8afad42
Revises: aba8d08aba8e
Create Date: 2025-10-18 01:58:18.586559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2254b8afad42'
down_revision = 'aba8d08aba8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'ai_insights')
    # ### end Alembic commands ###