"""add gin index on messages ai_insights for jsonb queries

Revision ID: 4164f32b9505
Revises: b0e8e4ba20a5
Create Date: 2025-10-26 02:39:58.229180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4164f32b9505'
down_revision = 'b0e8e4ba20a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_messages_ai_insights_gin', 'messages', ['ai_insights'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_ai_insights_gin', table_name='messages', postgresql_using='gin')
    # ### end Alembic commands ###