"""add ai_metadata to features

Revision ID: f8d3888eeeda
Revises: 2254b8afad42
Create Date: 2025-10-23 14:26:38.945658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d3888eeeda'
down_revision = '2254b8afad42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'ai_metadata')
    # ### end Alembic commands ###