"""Add contact_name and contact_email to customers

Revision ID: b3b869fc8e68
Revises: 6a7a6fdac979
Create Date: 2025-11-02 23:03:26.385435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b869fc8e68'
down_revision = '6a7a6fdac979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('contact_email', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_contact_email'), 'customers', ['contact_email'], unique=False)
    op.drop_index('idx_feature_messages_feature_id', table_name='feature_messages')
    op.drop_index('idx_feature_messages_message_id', table_name='feature_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_feature_messages_message_id', 'feature_messages', ['message_id'], unique=False)
    op.create_index('idx_feature_messages_feature_id', 'feature_messages', ['feature_id'], unique=False)
    op.drop_index(op.f('ix_customers_contact_email'), table_name='customers')
    op.drop_column('customers', 'contact_email')
    op.drop_column('customers', 'contact_name')
    # ### end Alembic commands ###