"""add title field to messages table

Revision ID: 38d042da8599
Revises: 4164f32b9505
Create Date: 2025-10-27 00:40:07.941733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d042da8599'
down_revision = '4164f32b9505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_title'), 'messages', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_title'), table_name='messages')
    op.drop_column('messages', 'title')
    # ### end Alembic commands ###