"""Add performance indexes

Revision ID: d42ca943b6be
Revises: 0ac37035cbc9
Create Date: 2025-10-10 15:10:30.158168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42ca943b6be'
down_revision = '0ac37035cbc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_features_last_mentioned', 'features', ['last_mentioned'], unique=False)
    op.create_index('idx_features_theme', 'features', ['theme_id'], unique=False)
    op.create_index('idx_features_workspace', 'features', ['workspace_id'], unique=False)
    op.create_index('idx_features_workspace_last_mentioned', 'features', ['workspace_id', 'last_mentioned'], unique=False)
    op.create_index('idx_features_workspace_theme', 'features', ['workspace_id', 'theme_id'], unique=False)
    op.create_index('idx_messages_workspace', 'messages', ['workspace_id'], unique=False)
    op.create_index('idx_messages_workspace_processed', 'messages', ['workspace_id', 'is_processed'], unique=False)
    op.create_index('idx_messages_workspace_sent', 'messages', ['workspace_id', 'sent_at'], unique=False)
    op.create_index('idx_themes_parent', 'themes', ['parent_theme_id'], unique=False)
    op.create_index('idx_themes_workspace', 'themes', ['workspace_id'], unique=False)
    op.create_index('idx_themes_workspace_sort', 'themes', ['workspace_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_themes_workspace_sort', table_name='themes')
    op.drop_index('idx_themes_workspace', table_name='themes')
    op.drop_index('idx_themes_parent', table_name='themes')
    op.drop_index('idx_messages_workspace_sent', table_name='messages')
    op.drop_index('idx_messages_workspace_processed', table_name='messages')
    op.drop_index('idx_messages_workspace', table_name='messages')
    op.drop_index('idx_features_workspace_theme', table_name='features')
    op.drop_index('idx_features_workspace_last_mentioned', table_name='features')
    op.drop_index('idx_features_workspace', table_name='features')
    op.drop_index('idx_features_theme', table_name='features')
    op.drop_index('idx_features_last_mentioned', table_name='features')
    # ### end Alembic commands ###