"""add_slack_team_id_to_workspaces

Revision ID: 120f915b7fb0
Revises: 543b81c8cc7b
Create Date: 2025-11-03 10:08:03.143775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120f915b7fb0'
down_revision = '543b81c8cc7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('slack_team_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_workspaces_slack_team_id'), 'workspaces', ['slack_team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_slack_team_id'), table_name='workspaces')
    op.drop_column('workspaces', 'slack_team_id')
    # ### end Alembic commands ###