"""update company size field to support new categories

Revision ID: 6a7a6fdac979
Revises: 38d042da8599
Create Date: 2025-10-27 14:37:55.915629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7a6fdac979'
down_revision = '38d042da8599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###