"""add_parent_theme_id_for_hierarchical_themes

Revision ID: f83c8eac3df4
Revises: a48c06b3f189
Create Date: 2025-10-07 09:48:02.394616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83c8eac3df4'
down_revision = 'a48c06b3f189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('parent_theme_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'themes', 'themes', ['parent_theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_column('themes', 'parent_theme_id')
    # ### end Alembic commands ###