"""Add use_cases to customers

Revision ID: 543b81c8cc7b
Revises: b3b869fc8e68
Create Date: 2025-11-02 23:31:33.236321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543b81c8cc7b'
down_revision = 'b3b869fc8e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('use_cases', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'use_cases')
    # ### end Alembic commands ###