"""Add data extraction fields table

Revision ID: 0ac37035cbc9
Revises: create_workspace_data_points
Create Date: 2025-10-10 11:32:37.605089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac37035cbc9'
down_revision = 'create_workspace_data_points'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_extraction_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_data_extraction_fields_workspace', 'data_extraction_fields', ['workspace_id'], unique=False)
    op.create_index('idx_data_extraction_fields_workspace_active', 'data_extraction_fields', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_data_extraction_fields_id'), 'data_extraction_fields', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_data_points_id'), 'workspace_data_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_data_points_id'), table_name='workspace_data_points')
    op.drop_index(op.f('ix_data_extraction_fields_id'), table_name='data_extraction_fields')
    op.drop_index('idx_data_extraction_fields_workspace_active', table_name='data_extraction_fields')
    op.drop_index('idx_data_extraction_fields_workspace', table_name='data_extraction_fields')
    op.drop_table('data_extraction_fields')
    # ### end Alembic commands ###